# this file is used for content understanding.
#######################---------------symptom---------------#######################
[SYMPTOM]
contain = ['症状', '表征', '现象', '症候', '表现', '征兆', '诊断']
name = 'SYMPTOM'

#######################---------------disease---------------#######################
[[DISEASE]]
contain = [
    '并发症',
    '并发',
    '一起发生',
    '一并发生',
    '一起出现',
    '一并出现',
    '一同发生',
    '一同出现',
    '伴随发生',
    '伴随',
    '共现',
]
not_contain = ['孩子', '训练']
name = 'COMPLICATION'
[[DISEASE]]
contain = ['治疗', '治', '医治', '治愈', '主治', '医']
name = 'CURE'
[[DISEASE]]
contain = [
    '预防',
    '防范',
    '防治',
    '避免',
]
not_contain = ['训练']
name = 'PREVENT'
[[DISEASE]]
contain = ['易感', '容易感染', '易发', '感染', '染上', '得上']
name = 'SUSCEPTIBLE'

#######################---------------food---------------#######################
[FOOD]
contain = [
    '饮食',
    '狗粮',
    '猫粮',
    '天然粮',
    '零食',
    '饮用',
    '吃',
    '食',
    '伙食',
    '膳食',
    '喝',
    '菜',
    '忌口',
    '补品',
    '保健品',
    '食谱',
    '菜谱',
    '食用',
    '食物',
    '补品',
    '猫能不能吃',
]
name = 'FOOD'

#######################---------------drug---------------#######################
[DRUG]
contain = ['药品', '药', '用药', '胶囊', '口服液', '炎片']
name = 'DRUG'

#######################---------------check---------------#######################
[CHECK]
contain = ['检查', '检查项目', '查出', '检查', '测出', '试出']
name = 'CHECK'

#######################---------------basic---------------#######################
[[BASIC]]
contain = ['购买', '买']
name = 'BUY'
[[BASIC]]
contain = ['区别', '区分', '分', '辨别', '怎么看', '鉴别', '分辨', '品种']
name = 'DISTINGUISH'

#######################---------------attribute---------------#######################
[[ATTRIBUTE]]
contain = ['纯种', '好坏', '纯', '品相', '纯度']
name = 'PURITY'
[[ATTRIBUTE]]
contain = ['公母']
name = 'SEX'
[[ATTRIBUTE]]
contain = ['价格', '钱', '费用']
name = 'PRICE'

#######################---------------question type---------------#######################
[[QUESTION]]
contain = ['注意事项', '注意', '需要注意']
name = 'CAUTION'
[[QUESTION]]
contain = [
    '什么时候',
    '周期',
    '多久',
    '多长时间',
    '多少时间',
    '几天',
    '几年',
    '多少天',
    '多少小时',
    '几个小时',
    '多少年',
    '时间',
]
name = 'WHEN'
[[QUESTION]]
contain = [
    '原因',
    '成因',
    '为什么',
    '怎么会',
    '怎样才',
    '咋样才',
    '怎样会',
    '如何会',
    '为啥',
    '为何',
    '如何才会',
    '怎么才会',
    '会导致',
    '会造成',
    '怎么回事',
]
name = 'CAUSE'
[[QUESTION]]
contain = ['什么', '啥', '有什么用', '有何用', '用处', '用途', '有什么', '用来做啥', '用来作甚']
name = 'WHAT'
[[QUESTION]]
contain = ['怎样', '怎么', '咋样', '咋', '如何', '咋才', '方式', '疗法', '方法', '怎么办', '咋办']
name = 'HOW'
[[QUESTION]]
contain = [
    '多大概率',
    '多大几率',
    '治好希望大么',
    '几率',
    '几成',
    '比例',
    '可能性',
    '能治',
    '可治',
    '可以治',
    '可以医',
]
not_contain = ['外形']
name = 'PROB'
[[QUESTION]]
name = 'WHICH'
contain = ['哪些']

#######################---------------constrain---------------#######################
[[AGE]]
contain = [
    '幼犬',
    '小猫',
    '小狗狗',
    '小奶狗',
    '小狗',
    '幼猫',
    '小猫咪',
    '幼犬期',
    '小奶猫',
    '幼',
    '金毛幼犬',
    '萨摩耶幼犬',
    '哈士奇幼犬',
    '六个月',
]
name = 'CHILD'
[[AGE]]
contain = ['成年', '成犬', '成猫']
name = 'ADULT'
[[AGE]]
contain = ['老年']
name = 'OLD'

[[SPECIES]]
contain = [
    '狗',
    '狗狗',
    '小狗狗',
    '小狗',
    '幼犬',
    '小奶狗',
    '流浪狗',
    '狗子',
    '幼犬期',
    '宠物狗狗',
    '母犬',
    '成犬',
    '养狗',
    '牧羊犬',
    '泰迪狗',
    '犬',
    '小型犬',
    '宠物狗',
    '金毛幼犬',
    '遛狗',
    '萨摩耶幼犬',
    '迷你杜宾犬',
    '哈士奇幼犬',
]
name = 'DOG'
[[SPECIES]]
contain = [
    '猫',
    '猫咪',
    '猫猫',
    '小猫',
    '幼猫',
    '小猫咪',
    '流浪猫',
    '小奶猫',
    '奶猫',
    '橘猫',
    '成猫',
    '公猫',
    '养猫',
    '家猫',
    '猫能不能吃',
    '蓝猫',
    '英短蓝猫',
    '宠物猫',
]
name = 'CAT'

[[SEX]]
contain = ['公', '公猫绝育', '公猫', '公狗']
not_contain = ['公母']
name = 'MALE'
[[SEX]]
contain = ['母', '母猫绝育', '母犬', '母狗', '母猫']
not_contain = ['公母']
name = 'FEMALE'

#######################---------------beauty---------------#######################
[[BEAUTY]]
contain = ['洗澡', '沐浴']
name = 'BATH'
[[BEAUTY]]
contain = ['美容', '剃毛', '剪指甲', '发腮', '剪毛']
name = 'COSMETIC'

#######################---------------healthy---------------#######################
[[HEALTHY]]
contain = [
    '驱虫',
    '跳蚤',
    '体外驱虫',
    '虫子',
    '蜱虫',
    '螨虫',
    '寄生虫',
    '虱子',
    '弓形虫',
    '体内驱虫',
    '跳蚤',
    '驱虫药',
    '球虫',
]
name = 'DEWORM'
[[HEALTHY]]
contain = ['疫苗', '打疫苗', '打狂犬疫苗', '狂犬疫苗', '打疫苗']
name = 'VACCINE'

#######################---------------nurse---------------#######################
[NURSE]
contain = ['护理', '护理方法', '照顾']
name = 'NURSE'

#######################---------------domesticate---------------#######################
[[DOMESTICATE]]  # 驯养
contain = ['训练', '训练方法', '教', '防止']
name = 'TRAIN'
[[DOMESTICATE]]
contain = ['养狗', '养猫', '遛狗', '喂养', '饲养', '喂食']
name = 'FEED'

#######################---------------breed---------------#######################
[[BREED]]  # 繁育
contain = ['发情', '发情期']
name = 'ESTRUS'
[[BREED]]
contain = ['配种', '交配']
name = 'MATING'
[[BREED]]
contain = ['绝育', '公猫绝育', '母猫绝育', '做绝育手术']
name = 'STERILIZATION'
[[BREED]]
contain = ['怀孕', '母猫怀孕', '母狗怀孕', '母犬怀孕']
name = 'PREGNANT'
[[BREED]]
contain = ['产后']
name = 'POSTPARTUM'
[[BREED]]
contain = ['流产']
name = 'ABORTION'
[[BREED]]
contain = ['生产', '繁殖']
name = 'PRODUCTION'
[[BREED]]
contain = ['难产']
name = 'DYSTOCIA'

#######################---------------part---------------#######################
[[PART]]
contain = ['头']
name = 'HEAD'
[[PART]]
contain = ['耳朵']
name = 'EAR'
[[PART]]
contain = ['眼睛']
name = 'EYE'
[[PART]]
contain = ['鼻子', '鼻']
name = 'NOSE'
[[PART]]
contain = ['脸', '面部']
name = 'FACE'
[[PART]]
contain = ['嘴']
name = 'MOUTH'
[[PART]]
contain = ['牙', '牙齿']
name = 'TEETH'
[[PART]]
contain = ['脖子', '颈部']
name = 'NECK'
[[PART]]
contain = ['胸', '胸部']
name = 'CHEST'
[[PART]]
contain = ['背', '背部']
name = 'BACK'
[[PART]]
contain = ['腿', '四肢', '前肢', '后肢', '后腿', '前腿']
name = 'LEG'
[[PART]]
contain = ['足', '脚', '掌', '爪子', '蹄子']
name = 'FOOT'
[[PART]]
contain = ['毛', '毛发']
name = 'HAIR'
[[PART]]
contain = ['皮肤']
name = 'SKIN'
[[PART]]
contain = ['腹', '肚子', '腹部']
name = 'ABDOMEN'
[[PART]]
contain = ['尾巴']
name = 'TAIL'
